### ISSUE TITLE
Characterization Reporting X'ed out

### ISSUE THREAD

**Issue by dashney** [PDXBES/ModelCatalog#1]
Both EMGAATS Model Registration and Characterization Reporting tools use model.valid BUT Characterization Reporting does not seem to know the parent_model_path so cannot validate the registration file portion of model.valid. The addition of valid.registration_file() at lines 97, 100 and 103 in model.valid is causing it to break but source of problem is that self.parent_model_path in valid_registration_file() is None when run through Characterization Reporting. 

 Traceback (most recent call last):
  File "<string>", line 28, in <module>
  File "C:\Users\dashney\Documents\Clones\ModelCatalog\ui\characterization_reporting.py", line 26, in create_characterization_model_dictionary
    self.model_catalog.add_models_from_model_catalog_db(self.model_catalog_db_data_io)
  File "C:\Users\dashney\Documents\Clones\ModelCatalog\businessclasses\model_catalog.py", line 128, in add_models_from_model_catalog_db
    self.add_models(self.create_models_from_model_catalog_db(model_catalog_db_data_io))
  File "C:\Users\dashney\Documents\Clones\ModelCatalog\businessclasses\model_catalog.py", line 38, in add_models
    self.check_for_valid_model(model)
  File "C:\Users\dashney\Documents\Clones\ModelCatalog\businessclasses\model_catalog.py", line 61, in check_for_valid_model
    if not model.valid:
  File "C:\Users\dashney\Documents\Clones\ModelCatalog\businessclasses\model.py", line 119, in valid
    if self.valid_emgaats_model_structure() and self.valid_required_simulations() and self.valid_registration_file():
  File "C:\Users\dashney\Documents\Clones\ModelCatalog\businessclasses\model.py", line 181, in valid_registration_file
    self.parent_model_registration_file_path = os.path.join(self.parent_model_path, "registration_file.json")
  File "C:\python27\ArcGIS10.3\Lib\ntpath.py", line 64, in join
    result_drive, result_path = splitdrive(path)
  File "C:\python27\ArcGIS10.3\Lib\ntpath.py", line 114, in splitdrive
    if len(p) > 1:
TypeError: object of type 'NoneType' has no len()

**Comment by dashney** [comment]
Resolved - Characterization Reporting reads in characterization models which have a parent_model_id NOT a parent_model_path. The valid_registration_file() function has to know the parent_model_path so if it is included in the overall valid() function this will cause Characterization Reporting to fail. Removed valid_registration_file() from overall valid() function and will test for this elsewhere.
